apiVersion: apps/v1
kind: Deployment
metadata:
  name: be42-deploy
spec:
  selector:
    matchLabels:
      app: be42
  template:
    metadata:
      labels:
        app: be42
    spec:
      containers:
        - name: be42
          image: 15.164.102.222:1588/return/be
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
