apiVersion: v1
kind: Service
metadata:
  name: be42-service
  labels:
    app: be42
spec:
  type: nodePort
  ports:
    - port: 8080
      nodePort: 31888
      protocol: TCP
  selector:
    app: be42
