apiVersion: v1
kind: Service
metadata:
  name: be42-service
  labels:
    app: be42
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      nodePort: 31888
  selector:
    app: be42
