apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe42-deploy
spec:
  selector:
    matchLabels:
      service: fe42
  template:
    metadata:
      labels:
        service: fe42
    spec:
      containers:
        - name: fe42
          image: 15.164.102.222:1588/return/fe
          ports:
            - containerPort: 80
              protocol: TCP
