apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: people-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: kube.people42.com
      http:
        paths:
          - path: /fe42
            pathType: Prefix
            backend:
              service:
                name: fe42-service
                port:
                  number: 80
          - path: /be42
            pathType: Prefix
            backend:
              service:
                name: be42-service
                port:
                  number: 8080
          - path: /redis
            pathType: Prefix
            backend:
              service:
                name: redis-service
                port:
                  number: 6666
          - path: /mariadb
            pathType: Prefix
            backend:
              service:
                name: mariadb-service
                port:
                  number: 3333