apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  labels:
    app: mariadb
spec:
  type: NodePort
  ports:
    - port: 3333
      protocol: TCP
      nodePort: 31333
  selector:
    app: mariadb
