apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6666
          env:
            - name: TZ
              value: "Asia/Seoul"
          command: ["redis-server", "--requirepass", "findromance!", "--port", "6379"]
