apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
spec:
  type: nodePort
  ports:
    - port: 6666
      nodePort: 31666
      protocol: TCP
  selector:
    app: redis
