apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
spec:
  type: NodePort
  ports:
    - port: 6666
      protocol: TCP
      nodePort: 31666
  selector:
    app: redis
